import { ShieldCheck } from "lucide-react";

export default function PrivacyPolicy() {
  return <main className="legal-page page-padding">
    <header className="legal-heading"><span className="icon-tile"><ShieldCheck size={23} /></span><div><p>Effective 30 September 2026</p><h1>Privacy Policy</h1><p>This policy explains what JIIT Shelf collects and how that information is used when you browse material, use Community, calculate an SGPA or contribute files.</p></div></header>
    <div className="legal-layout">
      <nav className="legal-index" aria-label="Privacy policy sections"><strong>On this page</strong><a href="#privacy-information">Information collected</a><a href="#privacy-use">How it is used</a><a href="#privacy-services">Services involved</a><a href="#privacy-choices">Your choices</a><a href="#privacy-contact">Contact</a></nav>
      <article className="legal-content">
        <section id="privacy-information"><h2>Information collected</h2><p>JIIT Shelf does not require an account. The information collected depends on the features you use.</p><ul><li><strong>Usage information:</strong> page views, visits, course opens, material clicks, Community visits and SGPA calculations. A randomly generated browser identifier and visit identifier are stored in your browser and recorded in hashed form for the site’s own aggregate statistics.</li><li><strong>Google Analytics:</strong> the site also uses Google Analytics 4, which may process device, browser, approximate location and interaction information using cookies or similar technologies.</li><li><strong>Community:</strong> the handle you enter, messages, likes, timestamps, room and a randomly generated client identifier are stored so chat can function. Community messages are visible to people who enter that room.</li><li><strong>Contributions:</strong> uploaded files, selected branch, semester, course and material type, and the credit name you provide are sent to a private Google Drive review folder.</li><li><strong>Browser storage:</strong> theme, selected course details, chat preferences, recent navigation, cached material listings and analytics identifiers may be kept locally on your device.</li></ul></section>
        <section id="privacy-use"><h2>How information is used</h2><p>Information is used to operate JIIT Shelf, load and organize study material, provide Community features, review contributions, understand aggregate usage, show public site statistics, maintain reliability and address misuse. JIIT Shelf does not sell personal information.</p><p>If a contribution is accepted, its file may be moved into the relevant public material folder and the supplied credit name may be displayed beside it. Do not submit private, confidential or personally identifying information inside a file.</p></section>
        <section id="privacy-services"><h2>Services involved</h2><p>JIIT Shelf relies on service providers to host and operate the site, including Vercel, Render, MongoDB, Google Drive and Google Analytics. These providers may process technical information under their own terms and privacy policies. Material links open Google Drive, where Google’s policies apply.</p><p>Operational records and chat content are retained for as long as reasonably needed to provide the service, moderate content, understand usage or maintain the project. Browser data remains until it expires or you clear site data. Hosting providers may keep their own security and request logs.</p></section>
        <section id="privacy-choices"><h2>Your choices</h2><p>You can clear JIIT Shelf’s local data through your browser settings and use browser privacy controls or extensions to restrict analytics cookies. Avoid using a real name in Community if you do not want it displayed publicly.</p><p>To request removal of a contribution credit, submitted file or Community message, email the address below with enough detail to locate it. Requests will be handled when ownership and the requested material can reasonably be identified.</p></section>
        <section id="privacy-security"><h2>Security</h2><p>Reasonable technical controls are used to protect the service, but no website, database or file transfer can be guaranteed completely secure. Never submit passwords, API keys, private records or sensitive personal information.</p></section>
        <section id="privacy-updates"><h2>Policy updates</h2><p>This policy may change when JIIT Shelf adds or changes features. The effective date at the top will be updated when material changes are made.</p></section>
        <section id="privacy-contact"><h2>Contact</h2><p>For privacy questions or removal requests, email <a href="mailto:jiitshelf@gmail.com">jiitshelf@gmail.com</a>.</p></section>
      </article>
    </div>
  </main>;
}
