import { ScrollText } from "lucide-react";

export default function Terms() {
  return <main className="legal-page page-padding">
    <header className="legal-heading"><span className="icon-tile"><ScrollText size={23} /></span><div><p>Effective 30 September 2026</p><h1>Terms of Use</h1><p>These terms apply when you access JIIT Shelf, use Community or submit study material.</p></div></header>
    <div className="legal-layout">
      <nav className="legal-index" aria-label="Terms sections"><strong>On this page</strong><a href="#terms-purpose">Purpose</a><a href="#terms-material">Study material</a><a href="#terms-community">Community</a><a href="#terms-contributions">Contributions</a><a href="#terms-contact">Contact</a></nav>
      <article className="legal-content">
        <section id="terms-purpose"><h2>Purpose and acceptance</h2><p>JIIT Shelf is an independent student resource that organizes study material for convenient access. By using it, you agree to these terms and the Privacy Policy. If you do not agree, do not use the service.</p><p>JIIT Shelf is not an official website of Jaypee Institute of Information Technology and is not a substitute for official notices, course instructions or academic advice.</p></section>
        <section id="terms-material"><h2>Study material</h2><p>Material is provided for study and reference. Although reasonable effort is made to organize useful and accurate resources, files may be incomplete, outdated, incorrectly labelled or contain errors. Verify schedules, syllabi, marks, policies and other important information through official sources.</p><p>You are responsible for using material lawfully and for respecting copyright, academic-integrity rules and any restrictions imposed by the original creator or institution. Access to a file does not transfer ownership or grant permission beyond what the rights holder allows.</p></section>
        <section id="terms-community"><h2>Community use</h2><p>Community rooms are public to people who enter them and do not require authentication. Do not post harassment, impersonation, spam, unlawful content, private information, malicious links or material that infringes another person’s rights. Do not attempt to disrupt, scrape, overload or bypass protections on the service.</p><p>Messages may be edited, removed or restricted when necessary to operate the service or address misuse. Because handles are user-entered, JIIT Shelf cannot guarantee that a displayed identity belongs to a particular person.</p></section>
        <section id="terms-contributions"><h2>Material contributions</h2><p>You may submit PDF or PPTX files for review. By submitting a file, you confirm that you have the right to share it and permit JIIT Shelf to review, rename, organize, reproduce and display it as part of the study-material collection.</p><p>Submission does not guarantee acceptance. Files may be rejected or removed without notice if they are inaccurate, unsuitable, duplicated, unsafe or raise ownership concerns. If accepted, the credit name you supplied may be displayed publicly. Do not upload answer sheets containing personal details, private documents, paid material, confidential files or content you are not allowed to distribute.</p></section>
        <section id="terms-tools"><h2>Tools and external services</h2><p>The SGPA estimator provides an estimate and may not reflect official calculations or results. Google Drive links, analytics and other third-party services are governed by their own terms. JIIT Shelf is not responsible for the availability, content or practices of external services.</p></section>
        <section id="terms-availability"><h2>Availability and responsibility</h2><p>JIIT Shelf is provided on an “as available” basis without guarantees of uninterrupted access, permanent file availability or fitness for a particular purpose. To the extent permitted by law, the project maintainers are not responsible for losses arising from reliance on site content, unavailable material, user submissions or Community activity.</p></section>
        <section id="terms-changes"><h2>Changes</h2><p>Features, material and these terms may be changed as the project evolves. Continued use after an update means you accept the revised terms. The effective date at the top identifies the current version.</p></section>
        <section id="terms-contact"><h2>Contact</h2><p>For questions, copyright concerns or content-removal requests, email <a href="mailto:jiitshelf@gmail.com">jiitshelf@gmail.com</a>.</p></section>
      </article>
    </div>
  </main>;
}
